### ISSUE TITLE
ccp-linear-search-3 fails to search for a number greater than the size of integer pointer

### ISSUE THREAD

**Issue by phreakyphoenix** [ayan-b/Linear-Search#162]
In the function lsearch the length of the array has to be passed, because from the decayed base pointer parameter, the sizeof(array_name) cannot actually determine array_size, but rather returns the size of the (int*) pointer, which is meaningless, and turns out to be 8 in most systems. So if one has 4 elements, it can lead to an unpredictable machine state, and for more than 8 elements, only the first 8 are going to be considered.

**Comment by phreakyphoenix** [comment]
I would like to work on this and also improve the coding style.

**Comment by ayan-b** [comment]
Sure, go ahead! Feel free to ping me if you face any difficulty. :smiley:

**Comment by phreakyphoenix** [comment]
There's the same problem in another file cpp-linear-search, I'm directly making a pr for that under this issue
